export { CargoIgnore } from "./cargo.ts"
export { MypyIgnore } from "./mypy.ts"
export { PyrightIgnore, mergePyrightConfigText } from "./pyright.ts"
export { TypeScriptIgnore } from "./typescript.ts"
export { ZigIgnore } from "./zig.ts"
