#!/usr/bin/env bun
/**
 * Globally links `ingraft` to the live TypeScript source in this workspace.
 *
 * Creates a shell wrapper that invokes `bun packages/cli/bin/ingraft.ts`
 * with the absolute repo path baked in, then symlinks it into `~/.bun/bin`
 * (or `--target`) as `ingraft`. Edits to .ts source are picked up immediately
 * on the next invocation — no rebuild needed.
 *
 * Usage:
 *   bun run link:dev               # install
 *   bun run unlink:dev             # remove
 *   bun scripts/link-dev.ts --target ~/.local/bin   # custom bin dir
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  writeFileSync
} from "node:fs"
import { homedir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const COMMAND_NAME = "ingraft"
const WRAPPER_FILENAME = "ingraft-dev"

const parseArgs = (argv: ReadonlyArray<string>) => {
  let remove = false
  let target: string | undefined
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === "--remove" || arg === "-r") {
      remove = true
    } else if (arg === "--target" || arg === "-t") {
      target = argv[++i]
    } else if (arg === "--help" || arg === "-h") {
      console.log(
        `Usage: bun scripts/link-dev.ts [--remove] [--target <dir>]\n\n` +
          `  --remove, -r    Remove the dev link.\n` +
          `  --target, -t    Bin directory to link into (default: ~/.bun/bin).`
      )
      process.exit(0)
    }
  }
  return { remove, target }
}

const defaultBinDir = (): string => {
  const bunBin = join(homedir(), ".bun", "bin")
  if (existsSync(bunBin)) return bunBin
  const localBin = join(homedir(), ".local", "bin")
  if (existsSync(localBin)) return localBin
  return bunBin
}

const main = () => {
  const { remove, target } = parseArgs(process.argv.slice(2))
  const scriptPath = fileURLToPath(import.meta.url)
  const cliRoot = resolve(dirname(scriptPath), "..")
  const wrapperSrc = join(cliRoot, "bin", WRAPPER_FILENAME)
  const sourceEntry = join(cliRoot, "bin", "ingraft.ts")
  const binDir = target ? resolve(target) : defaultBinDir()
  const linkPath = join(binDir, COMMAND_NAME)

  if (remove) {
    let removed = false
    if (existsSync(linkPath)) {
      rmSync(linkPath)
      removed = true
    }
    if (existsSync(wrapperSrc)) {
      rmSync(wrapperSrc)
      removed = true
    }
    console.log(
      removed
        ? `Removed ingraft dev link at ${linkPath}`
        : `No dev link found at ${linkPath} (nothing to remove).`
    )
    return
  }

  if (!existsSync(sourceEntry)) {
    console.error(`Cannot find CLI entry at ${sourceEntry}`)
    process.exit(1)
  }

  const wrapper = `#!/bin/sh
# Auto-generated by packages/cli/scripts/link-dev.ts
# Runs the live TypeScript source via Bun — no rebuild required.
exec bun ${JSON.stringify(sourceEntry)} "$@"
`
  writeFileSync(wrapperSrc, wrapper, { mode: 0o755 })
  chmodSync(wrapperSrc, 0o755)

  mkdirSync(binDir, { recursive: true })

  if (existsSync(linkPath)) {
    try {
      const current = readlinkSync(linkPath)
      if (resolve(dirname(linkPath), current) === wrapperSrc) {
        console.log(`ingraft already linked: ${linkPath} -> ${wrapperSrc}`)
        return
      }
    } catch {
      // existing path is a file, not a symlink — replace it
    }
    rmSync(linkPath)
  }

  symlinkSync(wrapperSrc, linkPath)

  console.log(`Linked ${linkPath} -> ${wrapperSrc}`)
  console.log(`Wrapper points at: ${sourceEntry}`)
  console.log(`Run \`${COMMAND_NAME} --help\` to verify.`)
  if (!process.env.PATH?.split(":").includes(binDir)) {
    console.log(`\nNote: ${binDir} is not on your PATH. Add this to your shell rc:`)
    console.log(`  export PATH="${binDir}:$PATH"`)
  }
}

main()
